cc_library(
    name = "proxy_client_lib",
    srcs = ["proxy_client.cc"],
    hdrs = ["proxy_client.h"],
    deps = [
        "//external:grpc++",
        "//src/main/cc/ipc:goma_ipc_lib",
        "//src/main/proto:command_server_cc_proto",
        "//src/main/proto:include_processor_cc_proto",
        "@com_google_absl//absl/strings",
    ],
)

cc_binary(
    name = "proxy_client",
    srcs = ["proxy_client_main.cc"],
    deps = [":proxy_client_lib"],
)

cc_binary(
    name = "fake_include_processor",
    srcs = ["fake_include_processor.cc"],
)
