
// File autogenerated by generate_compiler_proxy_info.py, do not modify.
#ifndef COMPILER_PROXY_INFO_H_
#define COMPILER_PROXY_INFO_H_
static const char kUserAgentString[] = "compiler-proxy built by olaola at e2544bc0bd6deb1154852a1414a9236c3a0ce897@1552539572 on 2019-03-14T18:30:19.839860Z ";
static const char kBuiltTimeString[] = "2019-03-14T18:30:19.839930Z";
static const char kBuiltDirectoryString[] = "/usr/local/google/home/olaola/goma/client/out";
static const char kBuiltUserNameString[] = "olaola";
static const char kBuiltHostNameString[] = "may.wat.corp.google.com";
static const char kBuiltRevisionString[] = "e2544bc0bd6deb1154852a1414a9236c3a0ce897@1552539572";
#endif // COMPILER_PROXY_INFO_H_
